// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEUsGC_Tm_jECrXtw2jK1MVWkVjiKU24c',
    appId: '1:716568401326:android:59b3046b7067625c8c243f',
    messagingSenderId: '716568401326',
    projectId: 'ai-gptchat',
    storageBucket: 'ai-gptchat.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyC_qE9SkWlrUOH8ptKOO0HXy_6QzGwC6jQ",
      authDomain: "totalis-f20af.firebaseapp.com",
      projectId: "totalis-f20af",
      storageBucket: "totalis-f20af.appspot.com",
      messagingSenderId: "578088673767",
      appId: "1:578088673767:web:ad2faa933fbdcacb0f9d42",
      measurementId: "G-R66MBPJVP3");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEm8hJ4W8Ji_S_scWBlNq4prjLAIpm09M',
    appId: '1:843632915571:ios:bca6f0d7b4a3d57f916606',
    messagingSenderId: '843632915571',
    projectId: 'claude-7f9c5',
    storageBucket: 'claude-7f9c5.appspot.com',
    androidClientId:
        '716568401326-0i0hmhrl1pvpohac8hq0i5k2po80c68d.apps.googleusercontent.com',
    iosClientId:
        '467057549060-kupi74jp45nr4g9n2chmt4j5k6u9tt3p.apps.googleusercontent.com',
    iosBundleId: 'com.totalis.admin.io',
  );
}
